"""Initial revision

Revision ID: 1a7a467849ac
Revises: 
Create Date: 2025-10-28 19:41:02.675502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7a467849ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema_user',
    sa.Column('userid', sa.Uuid(), nullable=False),
    sa.Column('userlogin', sa.String(length=50), nullable=False),
    sa.Column('userpassword', sa.String(length=70), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('useremail', sa.String(length=50), nullable=False),
    sa.Column('userrole', sa.Boolean(), nullable=False),
    sa.Column('userphoto', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('country',
    sa.Column('countrycode', sa.String(), nullable=False),
    sa.Column('countryname', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('countrycode')
    )
    op.create_table('genre',
    sa.Column('genreid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genrename', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('genreid')
    )
    op.create_table('hall',
    sa.Column('hallid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hallname', sa.String(length=50), nullable=False),
    sa.Column('rowamount', sa.Integer(), nullable=False),
    sa.Column('seatamount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('hallid')
    )
    op.create_table('movie',
    sa.Column('movieid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('moviename', sa.String(length=100), nullable=False),
    sa.Column('durationtime', sa.Interval(), nullable=False),
    sa.Column('releaseyear', sa.Integer(), nullable=False),
    sa.Column('agerate', sa.String(length=3), nullable=False),
    sa.Column('moviephoto', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('movieid')
    )
    op.create_table('profession',
    sa.Column('professionid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('professionname', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('professionid')
    )
    op.create_table('cast_member',
    sa.Column('memberid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('professionid', sa.Integer(), nullable=False),
    sa.Column('dateofbirth', sa.Date(), nullable=False),
    sa.Column('countrycode', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['countrycode'], ['country.countrycode'], ),
    sa.ForeignKeyConstraint(['professionid'], ['profession.professionid'], ),
    sa.PrimaryKeyConstraint('memberid')
    )
    op.create_table('cinema_session',
    sa.Column('sessionid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movieid', sa.Integer(), nullable=False),
    sa.Column('hallid', sa.Integer(), nullable=False),
    sa.Column('sessiondate', sa.Date(), nullable=False),
    sa.Column('sessiontime', sa.Interval(), nullable=False),
    sa.Column('ticketfee', sa.Numeric(), nullable=False),
    sa.Column('currencycode', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hallid'], ['hall.hallid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movieid'], ['movie.movieid'], ),
    sa.PrimaryKeyConstraint('sessionid')
    )
    op.create_table('movie_countries',
    sa.Column('movieid', sa.Integer(), nullable=False),
    sa.Column('countrycode', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['countrycode'], ['country.countrycode'], ),
    sa.ForeignKeyConstraint(['movieid'], ['movie.movieid'], ),
    sa.PrimaryKeyConstraint('movieid', 'countrycode')
    )
    op.create_table('movie_genres',
    sa.Column('movieid', sa.Integer(), nullable=False),
    sa.Column('genreid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genreid'], ['genre.genreid'], ),
    sa.ForeignKeyConstraint(['movieid'], ['movie.movieid'], ),
    sa.PrimaryKeyConstraint('movieid', 'genreid')
    )
    op.create_table('seat',
    sa.Column('hallid', sa.Integer(), nullable=False),
    sa.Column('rownumber', sa.Integer(), nullable=False),
    sa.Column('seatnumber', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hallid'], ['hall.hallid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hallid', 'rownumber', 'seatnumber')
    )
    op.create_table('movie_cast',
    sa.Column('movieid', sa.Integer(), nullable=False),
    sa.Column('memberid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['memberid'], ['cast_member.memberid'], ),
    sa.ForeignKeyConstraint(['movieid'], ['movie.movieid'], ),
    sa.PrimaryKeyConstraint('movieid', 'memberid')
    )
    op.create_table('seat_status',
    sa.Column('sessionid', sa.Integer(), nullable=False),
    sa.Column('rownumber', sa.Integer(), nullable=False),
    sa.Column('seatnumber', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sessionid'], ['cinema_session.sessionid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userid'], ['cinema_user.userid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('sessionid', 'rownumber', 'seatnumber')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seat_status')
    op.drop_table('movie_cast')
    op.drop_table('seat')
    op.drop_table('movie_genres')
    op.drop_table('movie_countries')
    op.drop_table('cinema_session')
    op.drop_table('cast_member')
    op.drop_table('profession')
    op.drop_table('movie')
    op.drop_table('hall')
    op.drop_table('genre')
    op.drop_table('country')
    op.drop_table('cinema_user')
    # ### end Alembic commands ###
