"""Editing movie pt2

Revision ID: 2a0e822a2e94
Revises: 60ccacfa2607
Create Date: 2025-11-09 19:59:59.404154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0e822a2e94'
down_revision: Union[str, Sequence[str], None] = '60ccacfa2607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('movie_cast_movieid_fkey'), 'movie_cast', type_='foreignkey')
    op.create_foreign_key(None, 'movie_cast', 'movie', ['movieid'], ['movieid'], ondelete='CASCADE')
    op.drop_constraint(op.f('movie_countries_movieid_fkey'), 'movie_countries', type_='foreignkey')
    op.create_foreign_key(None, 'movie_countries', 'movie', ['movieid'], ['movieid'], ondelete='CASCADE')
    op.drop_constraint(op.f('movie_genres_movieid_fkey'), 'movie_genres', type_='foreignkey')
    op.create_foreign_key(None, 'movie_genres', 'movie', ['movieid'], ['movieid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_genres', type_='foreignkey')
    op.create_foreign_key(op.f('movie_genres_movieid_fkey'), 'movie_genres', 'movie', ['movieid'], ['movieid'])
    op.drop_constraint(None, 'movie_countries', type_='foreignkey')
    op.create_foreign_key(op.f('movie_countries_movieid_fkey'), 'movie_countries', 'movie', ['movieid'], ['movieid'])
    op.drop_constraint(None, 'movie_cast', type_='foreignkey')
    op.create_foreign_key(op.f('movie_cast_movieid_fkey'), 'movie_cast', 'movie', ['movieid'], ['movieid'])
    # ### end Alembic commands ###
