"""Editing cast member

Revision ID: 4adeb4321ac9
Revises: 1a7a467849ac
Create Date: 2025-10-29 20:17:32.944247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4adeb4321ac9'
down_revision: Union[str, Sequence[str], None] = '1a7a467849ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cast_member_countrycode_fkey'), 'cast_member', type_='foreignkey')
    op.drop_column('cast_member', 'countrycode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cast_member', sa.Column('countrycode', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('cast_member_countrycode_fkey'), 'cast_member', 'country', ['countrycode'], ['countrycode'])
    # ### end Alembic commands ###
