"""Editing cast member pt4

Revision ID: 70258966d30c
Revises: ef1ef429a07e
Create Date: 2025-10-29 20:29:27.271020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70258966d30c'
down_revision: Union[str, Sequence[str], None] = 'ef1ef429a07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cast_member', sa.Column('professionid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cast_member', 'profession', ['professionid'], ['professionid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cast_member', type_='foreignkey')
    op.drop_column('cast_member', 'professionid')
    # ### end Alembic commands ###
