"""Editing seat status

Revision ID: 74ea779f3522
Revises: d8df8fa68ec1
Create Date: 2025-11-11 17:28:26.492963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ea779f3522'
down_revision: Union[str, Sequence[str], None] = 'd8df8fa68ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat_status', sa.Column('hallid', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seat_status', 'hallid')
    # ### end Alembic commands ###
