"""add column photo

Revision ID: 78398a8398ee
Revises: 176514735c97
Create Date: 2025-07-30 11:52:40.961276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78398a8398ee'
down_revision: Union[str, None] = '176514735c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cast_member_names_memberid_fkey', 'cast_member_names', type_='foreignkey')
    op.create_foreign_key(None, 'cast_member_names', 'cast_member', ['memberid'], ['memberid'])
    op.drop_constraint('cast_members_positions_memberid_fkey', 'cast_members_positions', type_='foreignkey')
    op.create_foreign_key(None, 'cast_members_positions', 'cast_member', ['memberid'], ['memberid'])
    op.add_column('cinema_user', sa.Column('userphoto', sa.Text(), nullable=True))
    op.drop_constraint('movie_cast_memberid_fkey', 'movie_cast', type_='foreignkey')
    op.drop_constraint('movie_cast_movieid_fkey', 'movie_cast', type_='foreignkey')
    op.create_foreign_key(None, 'movie_cast', 'cast_member', ['memberid'], ['memberid'])
    op.create_foreign_key(None, 'movie_cast', 'movie', ['movieid'], ['movieid'])
    op.drop_constraint('movie_countries_movieid_fkey', 'movie_countries', type_='foreignkey')
    op.create_foreign_key(None, 'movie_countries', 'movie', ['movieid'], ['movieid'])
    op.drop_constraint('movie_genres_movieid_fkey', 'movie_genres', type_='foreignkey')
    op.create_foreign_key(None, 'movie_genres', 'movie', ['movieid'], ['movieid'])
    op.drop_constraint('movie_name_movieid_fkey', 'movie_name', type_='foreignkey')
    op.create_foreign_key(None, 'movie_name', 'movie', ['movieid'], ['movieid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_name', type_='foreignkey')
    op.create_foreign_key('movie_name_movieid_fkey', 'movie_name', 'movie', ['movieid'], ['movieid'], ondelete='CASCADE')
    op.drop_constraint(None, 'movie_genres', type_='foreignkey')
    op.create_foreign_key('movie_genres_movieid_fkey', 'movie_genres', 'movie', ['movieid'], ['movieid'], ondelete='CASCADE')
    op.drop_constraint(None, 'movie_countries', type_='foreignkey')
    op.create_foreign_key('movie_countries_movieid_fkey', 'movie_countries', 'movie', ['movieid'], ['movieid'], ondelete='CASCADE')
    op.drop_constraint(None, 'movie_cast', type_='foreignkey')
    op.drop_constraint(None, 'movie_cast', type_='foreignkey')
    op.create_foreign_key('movie_cast_movieid_fkey', 'movie_cast', 'movie', ['movieid'], ['movieid'], ondelete='CASCADE')
    op.create_foreign_key('movie_cast_memberid_fkey', 'movie_cast', 'cast_member', ['memberid'], ['memberid'], ondelete='CASCADE')
    op.drop_column('cinema_user', 'userphoto')
    op.drop_constraint(None, 'cast_members_positions', type_='foreignkey')
    op.create_foreign_key('cast_members_positions_memberid_fkey', 'cast_members_positions', 'cast_member', ['memberid'], ['memberid'], ondelete='CASCADE')
    op.drop_constraint(None, 'cast_member_names', type_='foreignkey')
    op.create_foreign_key('cast_member_names_memberid_fkey', 'cast_member_names', 'cast_member', ['memberid'], ['memberid'], ondelete='CASCADE')
    # ### end Alembic commands ###
