"""add column photo to movie pt2

Revision ID: 787067341d36
Revises: 8112963032ff
Create Date: 2025-08-07 19:19:51.243309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '787067341d36'
down_revision: Union[str, None] = '8112963032ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('moviephoto', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'moviephoto')
    # ### end Alembic commands ###
