"""Add foreign key from seat_status to seat

Revision ID: 7c686f1e595f
Revises: 3689af982d8f
Create Date: 2025-06-24 20:40:28.220282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c686f1e595f'
down_revision: Union[str, None] = '3689af982d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cast_members_positions', 'created_at')
    op.drop_column('cast_members_positions', 'updated_at')
    op.drop_column('movie_cast', 'created_at')
    op.drop_column('movie_cast', 'updated_at')
    op.drop_column('movie_countries', 'created_at')
    op.drop_column('movie_countries', 'updated_at')
    op.drop_column('movie_genres', 'created_at')
    op.drop_column('movie_genres', 'updated_at')
    op.add_column('seat_status', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('seat_status', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('fk_seat_status_userid_user', 'seat_status', type_='foreignkey')
    op.create_foreign_key(None, 'seat_status', 'seat', ['hallid', 'rownumber', 'seatnumber'], ['hallid', 'rownumber', 'seatnumber'], ondelete='CASCADE')
    op.create_foreign_key(None, 'seat_status', 'cinema_user', ['userid'], ['userid'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seat_status', type_='foreignkey')
    op.drop_constraint(None, 'seat_status', type_='foreignkey')
    op.create_foreign_key('fk_seat_status_userid_user', 'seat_status', 'cinema_user', ['userid'], ['userid'])
    op.drop_column('seat_status', 'updated_at')
    op.drop_column('seat_status', 'created_at')
    op.add_column('movie_genres', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('movie_genres', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('movie_countries', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('movie_countries', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('movie_cast', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('movie_cast', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('cast_members_positions', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('cast_members_positions', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
