"""empty message

Revision ID: c1ed4ca1e5bb
Revises: aefa1372e486
Create Date: 2025-05-05 17:14:39.712739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ed4ca1e5bb'
down_revision: Union[str, None] = 'aefa1372e486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cast_member', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('cast_member', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('cast_member_names', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('cast_member_names', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('cast_members_positions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('cast_members_positions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('cinema_session', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('cinema_session', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('cinema_user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('cinema_user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('country', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('country', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('country_names', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('country_names', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('genre', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('genre', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('genre_names', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('genre_names', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('hall', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('hall', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('hall_names', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('hall_names', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('movie', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('movie', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('movie_cast', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('movie_cast', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('movie_countries', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('movie_countries', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('movie_genres', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('movie_genres', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('movie_name', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('movie_name', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('positions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('positions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('positions_names', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('positions_names', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('seat', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('seat', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seat', 'updated_at')
    op.drop_column('seat', 'created_at')
    op.drop_column('positions_names', 'updated_at')
    op.drop_column('positions_names', 'created_at')
    op.drop_column('positions', 'updated_at')
    op.drop_column('positions', 'created_at')
    op.drop_column('movie_name', 'updated_at')
    op.drop_column('movie_name', 'created_at')
    op.drop_column('movie_genres', 'updated_at')
    op.drop_column('movie_genres', 'created_at')
    op.drop_column('movie_countries', 'updated_at')
    op.drop_column('movie_countries', 'created_at')
    op.drop_column('movie_cast', 'updated_at')
    op.drop_column('movie_cast', 'created_at')
    op.drop_column('movie', 'updated_at')
    op.drop_column('movie', 'created_at')
    op.drop_column('hall_names', 'updated_at')
    op.drop_column('hall_names', 'created_at')
    op.drop_column('hall', 'updated_at')
    op.drop_column('hall', 'created_at')
    op.drop_column('genre_names', 'updated_at')
    op.drop_column('genre_names', 'created_at')
    op.drop_column('genre', 'updated_at')
    op.drop_column('genre', 'created_at')
    op.drop_column('country_names', 'updated_at')
    op.drop_column('country_names', 'created_at')
    op.drop_column('country', 'updated_at')
    op.drop_column('country', 'created_at')
    op.drop_column('cinema_user', 'updated_at')
    op.drop_column('cinema_user', 'created_at')
    op.drop_column('cinema_session', 'updated_at')
    op.drop_column('cinema_session', 'created_at')
    op.drop_column('cast_members_positions', 'updated_at')
    op.drop_column('cast_members_positions', 'created_at')
    op.drop_column('cast_member_names', 'updated_at')
    op.drop_column('cast_member_names', 'created_at')
    op.drop_column('cast_member', 'updated_at')
    op.drop_column('cast_member', 'created_at')
    # ### end Alembic commands ###
