"""Editing cast member pt2

Revision ID: dbf5870a5911
Revises: 4adeb4321ac9
Create Date: 2025-10-29 20:20:23.407967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf5870a5911'
down_revision: Union[str, Sequence[str], None] = '4adeb4321ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cast_member', sa.Column('membername', sa.String(length=100), nullable=False))
    op.drop_constraint(op.f('cast_member_professionid_fkey'), 'cast_member', type_='foreignkey')
    op.drop_column('cast_member', 'professionid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cast_member', sa.Column('professionid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('cast_member_professionid_fkey'), 'cast_member', 'profession', ['professionid'], ['professionid'])
    op.drop_column('cast_member', 'membername')
    # ### end Alembic commands ###
