"""Editing cast member pt3

Revision ID: ef1ef429a07e
Revises: dbf5870a5911
Create Date: 2025-10-29 20:27:11.387601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1ef429a07e'
down_revision: Union[str, Sequence[str], None] = 'dbf5870a5911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cast_member', sa.Column('countrycode', sa.String(), nullable=False))
    op.create_foreign_key(None, 'cast_member', 'country', ['countrycode'], ['countrycode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cast_member', type_='foreignkey')
    op.drop_column('cast_member', 'countrycode')
    # ### end Alembic commands ###
